experiment/urls.py
from django.urls import path
from .views import (
    experiment_tasks_day, get_outlines, save_task, delete_task, 
    experiment_tasks_long, save_gantt_data, get_gantt_data,
    experiment_tasks_apply, experiment_progress, get_task_details, 
    parse_task_pdf, delete_task_application, update_task_application,
    search_task_applications, experiment_tasks_run, save_device_run,
    get_device_run, delete_device_run, experiment_tasks_log,
    experiment_statistics_device, experiment_statistics_project,
    get_device_history, get_experiment_logs, get_experiment_log,
    save_experiment_log, delete_experiment_log, search_experiment_logs
)

app_name = 'experiment'

urlpatterns = [
    ## 设置任务路由
    # 设置日任务路由
    path('experiment_tasks_day/', experiment_tasks_day, name='experiment_tasks_day'),
    path('get_outlines/<str:project_code>/', get_outlines, name='get_outlines'),
    path('save_task/', save_task, name='save_task'),
    path('delete_task/', delete_task, name='delete_task'),
    # 设置长期任务路由
    path('experiment_tasks_long/', experiment_tasks_long, name='experiment_tasks_long'),
    path('save-gantt/', save_gantt_data, name='save_gantt_data'),
    path('get-gantt-data/', get_gantt_data, name='get-gantt-data'),

    # 设置紧急任务路由
    path('experiment_tasks_apply/', experiment_tasks_apply, name='experiment_tasks_apply'),

    ## 设置试验进度路由
    path('experiment_progress/', experiment_progress, name='experiment_progress'),

    
    # 获取任务详情的 API 路由
    path('api/task-details/<str:task_number>/', get_task_details, name='get_task_details'),
    path('api/parse-task-pdf/', parse_task_pdf, name='parse_task_pdf'),
    path('api/delete-task-application/', delete_task_application, name='delete_task_application'),
    path('api/update-task-application/', update_task_application, name='update_task_application'),
    path('api/search-task-applications/', search_task_applications, name='search_task_applications'),

    ## 设置试验统计路由
    # 设置试验运行统计路由
    path('experiment_tasks_run/', experiment_tasks_run, name='experiment_tasks_run'),
    path('api/save-device-run/', save_device_run, name='save_device_run'),
    path('api/get-device-run/<str:record_id>/', get_device_run, name='get_device_run'),
    path('api/delete-device-run/', delete_device_run, name='delete_device_run'),
    path('api/get-device-history/', get_device_history, name='get_device_history'),
    # 设置试验履历表路由
    path('experiment_tasks_log/', experiment_tasks_log, name='experiment_tasks_log'),
    path('api/get-experiment-logs/', get_experiment_logs, name='get_experiment_logs'),
    path('api/get-experiment-log/<str:log_id>/', get_experiment_log, name='get_experiment_log'),
    path('api/save-experiment-log/', save_experiment_log, name='save_experiment_log'),
    path('api/delete-experiment-log/', delete_experiment_log, name='delete_experiment_log'),
    path('api/search-experiment-logs/', search_experiment_logs, name='search_experiment_logs'),
    # 设置按照设备统计路由
    path('experiment_statistics_device/', experiment_statistics_device, name='experiment_statistics_device'),
    # 设置按照项目统计路由
    path('experiment_statistics_project/', experiment_statistics_project, name='experiment_statistics_project'),
]

index/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import user_login_ajax, index

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user_login.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='user_logout'),
    path('ajax_login_data/', user_login_ajax, name='ajax_login_data'),
    path('', index, name='index'),
]

lab_manage_sys_v1/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('index.urls', 'index'), namespace='index')),
    path('', include(('persons.urls', 'persons'), namespace='persons')),
    path('', include(('equipment.urls', 'equipment'), namespace='equipment')),
    path('', include(('experiment.urls', 'experiment'), namespace='experiment')),
    path('', include(('inventory.urls', 'inventory'), namespace='inventory')),
    path('', include(('dismantle.urls', 'dismantle'), namespace='dismantle')),
    path('', include(('comprehensive.urls', 'comprehensive'), namespace='comprehensive')),
    path('', include(('person_center.urls', 'person_center'), namespace='person_center')),
    path('', include(('admin_back.urls', 'admin_back'), namespace='admin_back')),
    re_path('media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
    re_path('static/(?P<path>.*)', serve, {"document_root": settings.STATIC_ROOT}),
]

experiment/views.py
import logging
import pdfplumber
import re
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from .models import *
from comprehensive.models import *
from django.utils.dateparse import parse_date
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from .models import GanttProject
import json
from datetime import datetime, timedelta
from equipment.models import Equipment
from django.db import models
from django.contrib import messages
import traceback  # 添加traceback模块
from django.db.models import Q, Sum, Count, Avg
from django.utils import timezone
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator
from django.db import transaction
from django.conf import settings
import os

# Create your views here.
@login_required
def get_outlines(request, project_code):
    try:
        outlines = Outlines.objects.filter(project=project_code).values('outline_num', 'outline_name')
        return JsonResponse({'outlines': list(outlines)})
    except Exception as e:
        logger.error(f"Error in get_outlines: {str(e)}")
        return JsonResponse({'outlines': [], 'error': str(e)}, status=500)

@login_required
def experiment_tasks_day(request):
    try:
        if not request.user.has_perm('experiment.view_tasks'):
            raise PermissionDenied
        tasks = Tasks.objects.exclude(task_status="已完成").order_by('task_date')
        user_has_permission = request.user.has_perm('experiment.change_tasks')

        # 获取所有设备编号
        equipment_list = Equipment.objects.values('equipment_id')

        # 为每个任务根据项目代号获取对应的 outlines
        for task in tasks:
            task.outlines = Outlines.objects.filter(project=task.project)

        context = {
            'page_title': '每日任务',
            'tasks': tasks,
            'user_has_permission': user_has_permission,
            'equipment_list': equipment_list,
        }
        return render(request, 'experiment_tasks_day.html', context)
    except PermissionDenied:
        context = {
            'error_message': '您没有权限查看此页面',
        }
        return render(request, 'experiment_tasks_day.html', context)


@login_required
@permission_required('experiment.change_tasks', raise_exception=True)
def save_task(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body.decode('utf-8'))
            task_id = data.get('task_id')
            task_status = data.get('task_status')
            project = data.get('project')
            sample_id = data.get('sample_id')
            test_content = data.get('test_content')
            equipment_id = data.get('equipment_id')
            work_content = data.get('work_content')
            outline = data.get('outline')
            task_date = data.get('task_date')
            client = data.get('client')
            experimenter = data.get('experimenter')
            schedule = data.get('schedule')
            remark = data.get('remark')

            # 解析并检查任务日期
            task_date = parse_date(task_date)
            if not task_date:
                return JsonResponse({'status': 'error', 'message': '任务日期格式必须为 "YYYY-MM-DD"'}, status=400)

            task, created = Tasks.objects.update_or_create(
                task_id=task_id,
                defaults={
                    'task_status': task_status,
                    'project': project,
                    'sample_id': sample_id,
                    'test_content': test_content,
                    'equipment_id': equipment_id,
                    'work_content': work_content,
                    'outline': outline,
                    'task_date': task_date,
                    'client': client,
                    'experimenter': experimenter,
                    'schedule': schedule,
                    'remark': remark,
                }
            )
            return JsonResponse({'status': 'success'})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=400)

    return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)


@login_required
@permission_required('experiment.delete_tasks', raise_exception=True)
def delete_task(request):
    if request.method == 'POST':
        task_id = request.POST.get('task_id')
        try:
            task = Tasks.objects.get(task_id=task_id)
            task.delete()
            return JsonResponse({'status': 'success'})
        except Tasks.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Task not found'}, status=404)
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=400)
    return JsonResponse({'status': 'error'}, status=400)

# 设置长期任务的视图
#=============================================================
@login_required
def experiment_tasks_long(request):
    context = {
        'page_title': '长期任务',
    }
    return render(request, 'experiment_tasks_long.html', context)
# 设置长期任务的甘特图视图函数
logger = logging.getLogger(__name__)
@csrf_exempt
@permission_required('experiment.change_ganttproject', raise_exception=True)
def save_gantt_data(request):
    if request.method == 'POST':
        logger.info(f"User: {request.user.username} is attempting to save Gantt data.")
        if not request.user.has_perm('experiment.change_ganttproject'):
            logger.warning(f"User: {request.user.username} does not have the required permission.")
            raise PermissionDenied

        data = json.loads(request.POST.get('data'))
        current_id = -1  # 从-1开始编号

        # 删除所有现有任务
        GanttProject.objects.all().delete()

        # 重新编号并保存任务
        for task in data['tasks']:
            task['id'] = current_id  # 为任务分配新的负数ID
            GanttProject.objects.update_or_create(
                project_id=current_id,
                defaults=generate_task_defaults(task)
            )
            current_id -= 1  # 递减ID

        return JsonResponse({'status': 'success', 'message': 'Gantt data saved successfully.'})
    return JsonResponse({'status': 'fail', 'message': 'Invalid request method.'})

def generate_task_defaults(task):
    return {
        'name': task.get('name', ''),
        'progress': task.get('progress', 0),
        'progress_by_worklog': task.get('progressByWorklog', False),
        'relevance': task.get('relevance', 0),
        'type': task.get('type', ''),
        'type_id': task.get('typeId', ''),
        'description': task.get('description', ''),
        'code': task.get('code', ''),
        'level': task.get('level', 0),
        'status': task.get('status', 'STATUS_ACTIVE'),
        'depends': task.get('depends', ''),
        'can_write': task.get('canWrite', True),
        'start': datetime.fromtimestamp(task.get('start') / 1000),  # 转换时间戳为日期时间
        'duration': task.get('duration', 0),
        'end': datetime.fromtimestamp(task.get('end') / 1000),  # 转换时间戳为日期时间
        'start_is_milestone': task.get('startIsMilestone', False),
        'end_is_milestone': task.get('endIsMilestone', False),
        'collapsed': task.get('collapsed', False),
        'assigs': task.get('assigs', []),
        'has_child': task.get('hasChild', False),
    }

def get_gantt_data(request):
    tasks = GanttProject.objects.all().values()
    task_list = []

    # 格式化任务数据
    for task in tasks:
        task_list.append({
            'id': task['project_id'],
            'name': task['name'],
            'progress': task['progress'],
            'progressByWorklog': task['progress_by_worklog'],
            'relevance': task['relevance'],
            'type': task['type'],
            'typeId': task['type_id'],
            'description': task['description'],
            'code': task['code'],
            'level': task['level'],
            'status': task['status'],
            'depends': task['depends'],
            'canWrite': task['can_write'],
            'start': int(task['start'].timestamp() * 1000),
            'duration': task['duration'],
            'end': int(task['end'].timestamp() * 1000),
            'startIsMilestone': task['start_is_milestone'],
            'endIsMilestone': task['end_is_milestone'],
            'collapsed': task['collapsed'],
            'assigs': task['assigs'],
            'hasChild': task['has_child']
        })

    response_data = {
        "tasks": task_list,
        "resources": [
            {"id": "tmp_1", "name": "Resource 1"},
            {"id": "tmp_2", "name": "Resource 2"},
            {"id": "tmp_3", "name": "Resource 3"},
            {"id": "tmp_4", "name": "Resource 4"}
        ],
        "roles": [
            {"id": "tmp_1", "name": "Project Manager"},
            {"id": "tmp_2", "name": "Worker"},
            {"id": "tmp_3", "name": "Stakeholder"},
            {"id": "tmp_4", "name": "Customer"}
        ],
        "canWrite": True,
        "canDelete": True,
        "canWriteOnParent": True,
        "canAdd": True
    }

    return JsonResponse({"status": "success", "data": response_data})

@login_required
def experiment_tasks_apply(request):
    if request.method == 'POST':
        try:
            # 处理试验时长，使用parse_chinese_duration函数
            run_time_str = request.POST.get('run')
            try:
                test_time = int(parse_chinese_duration(run_time_str))
            except:
                # 如果无法解析，尝试作为纯数字处理
                test_time = int(run_time_str) if run_time_str.isdigit() else 0
            
            # 创建新的 TaskApplication 实例
            task = TaskApplication(
                task_number=request.POST.get('taskNumber'),
                department=request.POST.get('department'),
                entrusted_person=request.POST.get('entrusted'),

experiment/templates/experiment_progress.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background" style="background-image: url({% static 'images/ban4.png' %});">
      <div class="container position-relative">
        <h1>{{ page_title }}</h1>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="/">首页</a></li>
            <li class="current"><a href={% url 'experiment:experiment_progress' %}>试验管理  /  </a>{{ page_title }}</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <!-- Starter Section Section -->
    <section id="starter-section" class="starter-section section">

      <div class="container" data-aos="fade-up">
        <p>Use this page as a starter for your own custom pages.</p>
      </div>

    </section><!-- /Starter Section Section -->

  </main>

{% endblock %}

experiment/templates/experiment_statistics_device.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background" style="background-image: url({% static 'images/ban4.png' %});">
      <div class="container position-relative">
        <h1>{{ page_title }}</h1>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="/">首页</a></li>
            <li class="current"><a href={% url 'experiment:experiment_statistics_device' %}>试验管理  /  </a>{{ page_title }}</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <!-- Starter Section Section -->
    <section id="starter-section" class="starter-section section">

      <div class="container" data-aos="fade-up">
        <p>1Use this page as a starter for your own custom pages.</p>
      </div>

    </section><!-- /Starter Section Section -->

  </main>

{% endblock %}

experiment/templates/experiment_statistics_projcet.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background" style="background-image: url({% static 'images/ban4.png' %});">
      <div class="container position-relative">
        <h1>{{ page_title }}</h1>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="/">首页</a></li>
            <li class="current"><a href={% url 'experiment:experiment_statistics_project' %}>试验管理  /  </a>{{ page_title }}</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <!-- Starter Section Section -->
    <section id="starter-section" class="starter-section section">

      <div class="container" data-aos="fade-up">
        <p>2Use this page as a starter for your own custom pages.</p>
      </div>

    </section><!-- /Starter Section Section -->

  </main>

{% endblock %}

experiment/templates/experiment_tasks_long.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main class="main">

    <!-- Page Title -->
    <div class="page-title dark-background" style="background-image: url({% static 'images/ban4.png' %});">
      <div class="container position-relative">
        <h1>{{ page_title }}</h1>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="/">首页</a></li>
            <li class="current"><a href={% url 'experiment:experiment_tasks_long' %}>试验管理  /  </a>{{ page_title }}</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <!-- Starter Section Section -->
    <section id="starter-section" class="starter-section section">

      <!-- 使用与头部一致的 container -->
      <div class="container-fluid" data-aos="fade-up">
        <!-- 使用 Bootstrap 卡片包裹 gantt.html 页面 -->
        <div class="card">
          <div class="card-body" style="height: 750px; overflow-y: auto;">
            <iframe src="{% static 'jQueryGantt-master/gantt.html' %}" width="100%" height="100%" frameborder="0"></iframe>
          </div>
        </div>
      </div>

    </section><!-- /Starter Section Section -->

  </main>

{% endblock %}