dismantle/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from .views import *

app_name = 'dismantle'

urlpatterns = [
    path('dismantle_apply/', dismantle_apply, name='dismantle_apply'),
    path('dismantle_register/', dismantle_register, name='dismantle_register'),
    path('dismantle_issue_summary/', dismantle_issue, name='dismantle_issue'),
    path('dismantle_PQCP/', dismantle_PQCP, name='dismantle_PQCP'),

]

equipment/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from .views import *

app_name = 'equipment'

urlpatterns = [
    # path('equipment_info/', equipment_information, name='equipment_information'),
    path('equipment_info/', EquipmentInformationView.as_view(), name='equipment_information'),
    path('save-equipment/', save_equipment, name='save_equipment'),
    path('delete-equipment/', delete_equipment, name='delete_equipment'),

    path('equipment_status/', equipment_status, name='equipment_status'),

    path('equipment_maintenance/', equipment_maintenance, name='equipment_maintenance'),
    path('add_maintenance_record/', add_maintenance_record, name='add_maintenance_record'),

    path('equipment_repair/', equipment_repair, name='equipment_repair'),
    path('equipment_medical_card/', equipment_medical_card, name='equipment_medical_card'),
    path('save_device_repair_application/', save_device_repair_application, name='save_device_repair_application'),
    path('get_device_repair_application_data/', get_device_repair_application_data, name='get_device_repair_application_data'),
    path('delete_device_repair_application/', delete_device_repair_application, name='delete_device_repair_application'),

    path('equipment_medical_card/', equipment_medical_card, name='equipment_medical_card'),

    path('equipment_analysis/', equipment_analysis, name='equipment_analysis'),
    # 添加供应商管理的URL配置
    path('supplier_management/', supplier_management, name='supplier_management'),
]

index/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import user_login_ajax, index

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user_login.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='user_logout'),
    path('ajax_login_data/', user_login_ajax, name='ajax_login_data'),
    path('', index, name='index'),
]

inventory/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from .views import *

app_name = 'inventory'

urlpatterns = [
    path('inventory_in/', inventory_in, name='inventory_in'),
    path('inventory_out/', inventory_out, name='inventory_out'),
    path('inventory_alarm/', inventory_alarm, name='inventory_alarm'),
    path('inventory_discard/', inventory_discard, name='inventory_discard'),
]

lab_manage_sys_v1/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('index.urls', 'index'), namespace='index')),
    path('', include(('persons.urls', 'persons'), namespace='persons')),
    path('', include(('equipment.urls', 'equipment'), namespace='equipment')),
    path('', include(('experiment.urls', 'experiment'), namespace='experiment')),
    path('', include(('inventory.urls', 'inventory'), namespace='inventory')),
    path('', include(('dismantle.urls', 'dismantle'), namespace='dismantle')),
    path('', include(('comprehensive.urls', 'comprehensive'), namespace='comprehensive')),
    path('', include(('person_center.urls', 'person_center'), namespace='person_center')),
    path('', include(('admin_back.urls', 'admin_back'), namespace='admin_back')),
    re_path('media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
    re_path('static/(?P<path>.*)', serve, {"document_root": settings.STATIC_ROOT}),
]

persons/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from .views import *

app_name = 'persons'

urlpatterns = [
    # 设置人员列表路由地址
    path('persons_list/', persons_list, name='persons_list'),
    path('save_person/', save_person, name='save_person'),
    path('delete_person/', delete_person, name='delete_person'),
    # 设置人员技能路由地址
    path('persons_skills/', persons_skills, name='persons_skills'),
    path('get_person_details/<int:person_id>/', get_person_details, name='get_person_details'),
    path('get_person_skill_data/<int:person_id>/<str:set_name>/', get_person_skill_data, name='get_person_skill_data'),
    path('update_skill/', update_skill, name='update_skill'),
    path('update_performance/', update_performance, name='update_performance'),
    # 设置任务负荷路由地址
    path('persons_tasks/', persons_tasks, name='persons_tasks'),
    path('save_task/', save_task, name='save_task'),
    path('delete_task/',delete_task, name='delete_task'),
    # 设置人员加班路由地址
    path('persons_overtime_apply/', persons_overtime_apply, name='persons_overtime_apply'),
    path('save_overtime_application/', save_overtime_application, name='save_overtime_application'),
    path('get_overtime_application_data/', get_overtime_application_data, name='get_overtime_application_data'),
    path('delete_overtime_application/', delete_overtime_application, name='delete_overtime_application'),
    path('persons_overtime_analysis/', persons_overtime_analysis, name='persons_overtime_analysis'),
    
]

templates/base_admin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{title}}</title>
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/google-fonts/google.fonts.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/fontawesome-free/css/all.min.css' %}">
  <!--
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  -->
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/jqvmap/jqvmap.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE/dist/css/adminlte.min.css'%}">
  <link rel="stylesheet" href="{% static 'AdminLTE/dist/css/common.css'%}">
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/daterangepicker/daterangepicker.css' %}">

  <link rel="stylesheet" href="{% static 'AdminLTE/plugins/summernote/summernote-bs4.min.css' %}">
  <script src="{% static 'AdminLTE/plugins/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'AdminLTE/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
 {% block ext_css %}
 {% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'person_center:person_center' %}" class="nav-link">首页</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'index:index' %}" class="nav-link">返回</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="#" class="brand-link">
      <img src="{% static 'AdminLTE/dist/img/AdminLTELogo.png'%}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">系统后台</span>
    </a>
    <div class="sidebar">
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'AdminLTE/dist/img/user2-160x160.jpg'%}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">管理员</a>
        </div>
      </div>
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-header">运营管理</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-calendar-alt"></i>
              <p>
                新订单
                <span class="badge badge-info right">2</span>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                订单管理
              </p>
            </a>
          </li>

          <li class="nav-header">用户管理</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-calendar-alt"></i>
              <p>
                用户信息
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                状态异常会员
              </p>
            </a>
          </li>

          <li class="nav-header">基础信息</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-ellipsis-h"></i>
              <p>区域维护</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-file"></i>
              <p>Documentation</p>
            </a>
          </li>
          <li class="nav-header">商品管理</li>
            <li class="nav-item">
            <a href="/goods/cate_index" class="nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>商品分类维护</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="/goods/index" class="nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>商品信息维护</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>商品上下架</p>
            </a>
          </li>
          <li class="nav-header">系统管理</li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-circle text-danger"></i>
              <p class="text">用户管理</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-circle text-warning"></i>
              <p>角色管理</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-circle text-info"></i>
              <p>权限管理</p>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </aside>
  {%block content%}
  {%endblock%}

  <aside class="control-sidebar control-sidebar-dark">
  </aside>
</div>

<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<script src="{% static 'AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/chart.js/Chart.min.js' %}"></script>

<script src="{% static 'AdminLTE/plugins/sparklines/sparkline.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/summernote/summernote-bs4.min.js' %}"></script>
<script src="{% static 'AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<script src="{% static 'AdminLTE/dist/js/adminlte.js' %}"></script>

<script src="{% static 'AdminLTE/dist/js/pages/dashboard.js' %}"></script>

{% block ext_js %}
{% endblock%}
</body>
</html>

templates/base_page.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>SAGW 实验中心管理系统</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    
    <!-- Favicons -->
    <link href="{% static 'images/logo_sagw_blue.png' %}" rel="icon">
    <link href="{% static 'images/logo_sagw_blue.png' %}" rel="apple-touch-icon">
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    
    <!-- Vendor CSS Files -->
    <link href="{% static 'css/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'css/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    
    <!-- Main CSS File -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    
    <!-- =======================================================
    * Template Name: UpConstruction
    * Template URL: https://bootstrapmade.com/upconstruction-bootstrap-construction-website-template/
    * Updated: Jun 29 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>
<header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="/" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <img src="{% static 'images/logo_sagw_blue.png' %}" alt="">
        <h1 class="sitename">实验中心管理系统</h1> <span>.</span>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="/" class="{% if request.path == '/' %}active{% endif %}">首页</a></li>
          <li class="dropdown"><a href="{% url 'persons:persons_list' %}" class="{% if 'persons_list' in request.path %}active{% endif %}"><span>人员管理</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li><a href="{% url 'persons:persons_list' %}">人员清单</a></li>
              <li><a href="{% url 'persons:persons_skills' %}">人员能力</a></li>
              <li><a href="{% url 'persons:persons_tasks' %}">人员负荷</a></li>
              <li><a href="{% url 'persons:persons_overtime' %}">人员加班</a></li>
            </ul>
          <li class="dropdown"><a href="{% url 'equipment:equipment_information' %}" class="{% if 'equipment_info' in request.path %}active{% endif %}"><span>设备管理</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li class="dropdown"><a href="{% url 'equipment:equipment_information' %}"><span>设备信息</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                <ul>
                  <li><a href="#">设备列表</a></li>
                  <li><a href="#">新增设备</a></li>
                  <li><a href="#">更新信息</a></li>
                </ul>
              <li><a href="{% url 'equipment:equipment_status' %}">设备状态</a></li>
              <li><a href="{% url 'equipment:equipment_maintenance' %}">设备保养</a></li>
              <li class="dropdown"><a href="{% url 'equipment:equipment_repair' %}"><span>设备维修</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                <ul>
                  <li><a href="#">维修申请</a></li>
                  <li><a href="#">维修进度</a></li>
                  <li><a href="#">设备病历</a></li>
                  <li><a href="#">汇总分析</a></li>
                </ul>
            </ul>
          <li class="dropdown"><a href="{% url 'experiment:experiment_tasks' %}" class="{% if 'experiment_tasks' in request.path %}active{% endif %}"><span>试验管理</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li class="dropdown"><a href="{% url 'experiment:experiment_tasks' %}"><span>试验任务</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                <ul>
                  <li><a href="#">每日任务</a></li>
                  <li><a href="#">长期任务</a></li>
                  <li><a href="#">紧急任务</a></li>
                </ul>
              <li class="dropdown"><a href="{% url 'experiment:experiment_progress' %}"><span>试验进度</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                <ul>
                  <li><a href="#">信息维护</a></li>
                  <li><a href="#">进度概览</a></li>
                  <li><a href="#">拖点汇总</a></li>
                </ul>
              <li class="dropdown"><a href="{% url 'experiment:experiment_statistics' %}"><span>试验统计</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                <ul>
                  <li><a href="#">按设备统计</a></li>
                  <li><a href="#">按项目统计</a></li>
                </ul>
            </ul>
          <li class="dropdown"><a href="{% url 'inventory:inventory_in' %}" class="{% if 'inventory_in' in request.path %}active{% endif %}"><span>库存管理</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li><a href="{% url 'inventory:inventory_in' %}">入库登记</a></li>
              <li><a href="{% url 'inventory:inventory_out' %}">出库登记</a></li>
              <li><a href="{% url 'inventory:inventory_alarm' %}">库存预警</a></li>
              <li><a href="{% url 'inventory:inventory_discard' %}">报废汇总</a></li>
            </ul>
          <li class="dropdown"><a href="{% url 'dismantle:dismantle_apply' %}" class="{% if 'dismantle_apply' in request.path %}active{% endif %}"><span>拆解管理</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li><a href="{% url 'dismantle:dismantle_apply' %}">拆解任务申请</a></li>
              <li><a href="{% url 'dismantle:dismantle_register' %}">拆解结果登记</a></li>
              <li><a href="{% url 'dismantle:dismantle_issue' %}">失效问题汇总</a></li>
              <li><a href="{% url 'dismantle:dismantle_PQCP' %}">PQCP登记</a></li>
            </ul>
          <li class="dropdown"><a href="{% url 'comprehensive:report_register' %}" class="{% if 'report_register' in request.path %}active{% endif %}"><span>综合管理</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              <li><a href="{% url 'comprehensive:report_register' %}">报告出具登记</a></li>
              <li><a href="{% url 'comprehensive:report_delay' %}">拖延报告汇总</a></li>
              <li><a href="{% url 'comprehensive:report_analysis' %}">报告汇总分析</a></li>
            </ul>
          <li><a href="{% url 'person_center:person_center' %}" class="{% if 'personal' in request.path %}active{% endif %}">个人中心</a></li>
            
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>



{% block content %}

        
{% endblock %}

<!-- ======================================================= -->
{#页脚内容#}
    <footer id="footer" class="footer dark-background">
    
    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-4 col-md-6 footer-about">
          <a href="/" class="logo d-flex align-items-center">
            <span class="sitename">SAGW Laboratory</span>
          </a>
          <div class="footer-contact pt-3">
            <p>上海市嘉定区汇旺路600号</p>
            <p>上海汽车变速器有限公司实验中心</p>
            <p class="mt-3"><strong>Phone:</strong> <span>130-5231-0560</span></p>
            <p><strong>Email:</strong> <span>yumeng@sagw.com</span></p>
          </div>
          <div class="social-links d-flex mt-4">
            <a href=""><i class="bi bi-twitter-x"></i></a>
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-linkedin"></i></a>
          </div>
        </div>
    
        <div class="col-lg-2 col-md-3 footer-links">
          <h4>友情链接</h4>
          <ul>
            <li><a href="/">首页</a></li>
            <li><a href="{% url 'persons:persons_list' %}">人员管理</a></li>
            <li><a href="{% url 'equipment:equipment_information' %}">设备管理</a></li>
            <li><a href="{% url 'experiment:experiment_tasks' %}">试验管理</a></li>
            <li><a href="{% url 'inventory:inventory_in' %}">库存管理</a></li>
          </ul>
        </div>
    
        <div class="col-lg-2 col-md-3 footer-links">
          <h4>重点业务</h4>
          <ul>
            <li><a href="#">材料开发</a></li>
            <li><a href="#">理化分析</a></li>
            <li><a href="#">接头试验</a></li>
            <li><a href="#">精密测量</a></li>
            <li><a href="#">台架试验</a></li>
            <li><a href="#">整车试验</a></li>
          </ul>
        </div>
    
        <div class="col-lg-2 col-md-3 footer-links">
          <h4>数据分析</h4>
          <ul>
            <li><a href="{% url 'persons:persons_tasks' %}">人员负荷</a></li>
            <li><a href="#">设备运行</a></li>
            <li><a href="#">项目管理</a></li>
            <li><a href="#">报告拖延</a></li>
            <li><a href="#">试后失效</a></li>
          </ul>
        </div>
    
        <div class="col-lg-2 col-md-3 footer-links">
          <h4>当前任务</h4>
          <ul>
            <li><a href="#">前期准备</a></li>
            <li><a href="#">紧急任务</a></li>
          </ul>
        </div>
    
      </div>
    </div>
    
    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">SAGW Laboratory</strong> <span>All Rights Reserved</span></p>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
{#        Designed by <a href="{% url 'person_center:person_center' %}">MengYu</a>#}
        Designed by <a href="#">MengYu</a>
      </div>
    </div>
    
    </footer>

<!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'css/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'css/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'css/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'css/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'css/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'css/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'css/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'css/vendor/purecounter/purecounter_vanilla.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>